Test test test---
title: "Git to BASH"
author: "JR"
date: "10/19/2020"
output: html_document
---
HOPEFULLY THIS WORKS !!!
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Our first objective today will be to sync to the class github. We will
go over a few needed things to establish git connections:

Sign up for github -- if you already have please make a new github repository.


## The very first thing we need to do is make the github website communicate
with Fiji. Once this relationship is established, you don't need to do this again :)

Navigate to your home directory on fiji ~/IDENTIKEY

```
cd ~
ls -lah
```

Note that there is a .ssh folder that you can place these unique keys to let
servers communicate securely. We can check to see if a key already exists.
If it doesn't we will generate one with the with ssh-keygen command.

```
cd .ssh
ls -lah
# If it exists already, you can check out the public key using cat
cat id_rsa.pub
```


This will reveal the public ssh key for fiji. If we don't have a key in this file already,
let's create one:

```
ssh-keygen -t rsa
```

The default name id_rsa should work just fine.
Then cat the contents of the public key file (id_rsa.pub) and copy to clipboard.

Now let's got to your github website. You will need to sign into your github account first.

On the top right there is a drop down
menu. Click on "Settings". Now you will see on the left side there is a list of
options. Click on "SSH and GPG Keys" There already be some keys in there or blank.
Either way click "Add new key" on top right (green button). Paste in the new
public SSH key we just generated.

You may also want to go to your local computer shell .ssh folder (same place).
Generate a key and paste into github as done above. This way your local terminal
(not fiji server) can push to github too. Basically any machine(s) you want to
talk to github need this "handshake" SSH key.

Cool we are all connected !

Now that we're familiar with SSH keys, we can set-up
an authorized key on fiji so that you don't need to use your
password each time.

We will be adding the public key to the `~/.ssh/authorized_keys` file.
You'll create a key on your local computer. In windows you can use
puttygen to create the key and on Mac or Linux you can use ssh-keygen
the same way.

The instructions for creating a key with putty are here and detailed.
https://www.ssh.com/ssh/putty/windows/puttygen

The location of the key file should be in cd ~/.ssh for Mac and
in Windows it should be in C:/Users/<username>/.ssh

Then as above for github, you'll copy the public key to your clipboard
and paste it into `~/.ssh/authorized_keys`

```
nano ~/.ssh/authorized_keys
# Then paste in the key and save file.
```
This will allow you to log-in to fiji without having to type your
password in each time.


-------------------------------------------------------------

Now let's see how this all it works:

Navigate to /scratch/Shares/rinnclass/<your name>

# Let's clone the class git repository from GitHub

On the CLASS_2021 GitHub site, click the Code dropdown, select SSH
as your method on connecting and then click the clipboard icon which will
copy the url to your clipboard. You can then paste it here.

```
git clone <paste-ssh-link>
```
Voila you are connected to our CLASS_2021 git repository.

Let's explore a bit the .git directory where the repository exists.
In this directory, it keeps track of the fact that the remote repository
is this one here on GitHub and you can synchronize your local repository
with the remote anytime.

While in class, I'll make a change to the git and then have you update
your local repository with those changes
using the git pull command.

```
git pull
```

Note that multiple people could make changes to the same file which results in conflicting versions.
Nicely, git will not allow any commits to be pushed to the remote without asking you to resolve the conflicts
between the two versions of a file.

You can minimize the likelihood of having a file conflict if you `git pull` at the
start of each session.

Another way to avoid conflicting changes is to create a new branch and eventually you'll
be able to merge that branch into the code in the main branch.
Often, the practice is to make new branches corresponding to new features in the code of a project.
In our case, that will correspond to new analyses. Also, this allows a mechanism for new
code to be verified before it ends up in the master branch.


## Create a new branch and make some changes.

You can have as many branches as you want, so in order to avoid conflicts in this case
we'll give you each a branch! Using `git checkout -b` allows you to switch branches,
but it will also create a branch with that name if one doesn't exist.

```
git checkout -b <your-name>
```

Now use git status to see which branch you're on

```
git status
```

## Make some edits and make your first commit

Let's create a new file and type whatever, then you can  `git add`

```
nano test.Rmd
# Type in something
# Save file
git status
git add test.Rmd
git status
```

Do you see a new item (test.Rmd) that git noticed was made and ready to sync?

Now we need to commit these changes that have been staged

```
git commit -m "Created a new test file."
```

Typically you'll want to be very specific about what you write in the git commit.

Now you should be on the students branch of the git site. Sometimes this can get
buggy so you can also trying forcing a branch move:

```
git push -u origin NEW-BRANCH-NAME
```

Or you may receive an error something like:
fatal: The current branch students has no upstream branch.
To push the current branch and set the remote as upstream, use

    git push --set-upstream origin students

Just paste in that and it will work.

Ok let's update the github website from the terminal!

```
git status
git add test.Rmd
git commit -m "(put the notes you want on what was done inside the quotes)"
git push
# type git push again and you should see "up to date"

! Always remember to PUSH before you END a session !
! Always remember to PULL before you START a session !
```

If you are collaborating on a git-branch when you start a session it's always good to "pull" any updates since you last logged in. this can easily be done by:

```
git pull
```

If you want to check out previous changes you can use :

```
git log
git diff Xsum1 Xsum2
```

This will show you all the changes -- you can also do this a bit more user friendly on git website.

Finally we need a text file titled ".gitignore" put all the file types you don't want to track. These are large files such as .csv or .pdf etc here are some examples


```
touch .gitignore
nano .gitignore
# add extensions of files that are large (pdf, images etc)
# for this class copy and paste the following into .gitignore using nano
```


.Rproj.user
.Rhistory
.RData
.Ruserdata
*.bam
*.pdf
*.Rproj
*.Rproj
*.pdf
*.png
*results*
*figures*
*bam*
*.tmp
*html
*.bed
*_rslurm*
*.chain
*.bed*
*data*
*.txt
*.csv
*archive*



-----------------------------------------------
Let's all get set up on fiji and github website using this info ....
