---
title: "sample_sheet_setup"
author: "JR"
date: "9/23/2020"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ENCODExplorer)
library(tidyverse)
```

# >>>>>>>>>>>>>>>>>>>>>>>>>>>

## Let's see what to do here but likely the API hack



```{r}
library(tidyverse)
library(httr)
install.packages("janitor")
library(janitor)

contstruct_query <- function(experiment_accession,
                             base_url = "https://www.encodeproject.org/report.tsv?",
                             file_format = "fastq",
                             type = "File", 
                             status = "released",
                             fields = c("accession", "read_count", "md5sum",
                                        "controlled_by", "paired_end",
                                        "paired_with", "replicate", "target")) {
  query <- paste(list(paste0("type=", type), 
        paste0("status=", status),
        paste0("file_format=", file_format),
        paste0("dataset=%2Fexperiments%2F", experiment_accession, "%2F"),
        map_chr(fields, ~paste0("field=", .))) %>%
          flatten(),
       collapse = "&")
  url <- paste0(base_url, query)
  return(url)
}
get_fastq_info <- function(experiment_accession) {
  request <- GET(contstruct_query(experiment_accession)) 
  body <- read_tsv(content(request, "text"), skip = 1)
  return(body)
}
# Read in the experiment report downloaded from Encode
# we will only use the Accession column 
# Here we'll retrieve the read_count and md5 sum 
# as well as the file accession (with some other metadata)
# for the fastq files associated with each experiment.





fastq_info <- read.table("Best_class_full_controls.tsv",
                        skip = 1, sep = "\t", header = T) %>%
  dplyr::select(Accession) %>%
  dplyr::rename(experiment_accession = Accession) %>%
  distinct() %>%
  mutate(fastq_info = map(experiment_accession, ~get_fastq_info(.))) %>%
  unnest(fastq_info) %>%
  dplyr::rename(file_accession = Accession) %>%
  clean_names()


write.csv(fastq_info, "final_files_md5sum.csv")
```

```{r}
controls <- fastq_info %>% filter(is.na(controlled_by)) %>%
  dplyr::rename(control_accession = file_accession) %>%
  dplyr::select(control_accession) %>%
  mutate(has_control = TRUE)

write.csv(controls, "controls.csv")

experiments <- fastq_info %>% filter(!is.na(controlled_by)) %>%
  mutate(control_accession = gsub("files", "", gsub("/", "", controlled_by))) %>%
  separate_rows(control_accession, sep = ",") %>%
  merge(controls, all.x = T)
no_controls <- experiments %>%
  filter(is.na(has_control))

write.csv(experiments, "experiments.csv")
write.csv(no_controls, "no_controls.csv")







table(experiments$has_control)
```























