---
title: "Class project"
author: "OL"
date: "3/12/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
source('util/intersect_functions.R')
```

FILES
```{r}
# scatterplot x: K562 % dbp and HepG

peak_occurence_df_2020 <- read.csv(file = '/scratch/Shares/rinnclass/data/2020_peak_occurence_df.csv')
head(peak_occurence_df_2020)

peak_occurence_df_new <- read.csv(file = '/scratch/Shares/rinnclass/Nina/CLASS_2021/analysis/01_global_peak_properties/results/peak_occurence_dataframe.csv')
head(peak_occurence_df_new)
```

FILTERING THE FILES BY RESERVOIR
```{r}
res_genes <- X2020_peak_occurence_df %>% filter(X2020_peak_occurence_df$reservoir == 1)
res_gene_names <- res_genes$gene_name
#goal: get a list of reservoir gene names from the old data.

res_genes_2021 <- peak_occurence_df %>% filter(peak_occurence_df$gene_name %in% res_gene_names)
res_gene_names_2021 <- res_genes_2021$gene_name
#goal: filter out the same genes in the new data

head(res_gene_names_2021)

clean_res_genes_2021 <- res_genes_2021[-c(475),]
which(grepl('ENSG00000258325.2', clean_res_genes_2021$gene_id))
clean2_res_genes_2021 <- clean_res_genes_2021[-c(704),]

comparison_df <- merge(res_genes, clean2_res_genes_2021)

#need to remove ENSG00000254093.9 and ENSG00000258325.2
#done

total_dbp_2021 <- length(clean2_res_genes_2021$number_of_dbp)
total_dbp_2020 <- length(res_genes$number_of_dbp)

#normalizes the dbp count

normalized_ratio_res21_res20 <- clean2_res_genes_2021$number_of_dbp/161 %/% res_genes$number_of_dbp/460

#finds the ratio of expression of each gene, not normalized to total reads.
clean2_res_genes_2021 <- subset(clean2_res_genes_2021, select = -c(8))
clean2_res_genes_2021 <- cbind(clean2_res_genes_2021, normalized_ratio_res21_res20)


#adds the ratio to the 2021 df. Should show which genes are up and down regulated in liver cells.


normalized_2021 <- clean2_res_genes_2021 %>%
    dplyr::select(gene_id, gene_type, number_of_dbp) %>%
    dplyr::rename(num_dbp_HEPG2 = number_of_dbp)
  
normalized_2020 <- X2020_peak_occurence_df %>%
    dplyr::select(gene_id, gene_type, number_of_dbp) %>%
    dplyr::rename(num_dbp_K562 = number_of_dbp)

#Nina's

num_dbp_2020 <- peak_occurence_df_2020 %>%
  dplyr::select(gene_id, gene_type, number_of_dbp) %>%
  dplyr::rename(num_dbp_K562 = number_of_dbp)
num_reservoir_new_data <- res_genes_2021 %>%
  dplyr::select(gene_id, number_of_dbp) %>%
  dplyr::rename(num_dbp_HepG2 = number_of_dbp)


comparison_df <- merge(num_dbp_2020, num_reservoir_new_data)

comparison_df <-comparison_df %>% mutate(dbp_HepG2_ratio = num_dbp_HepG2/161) #161
comparison_df <- comparison_df %>% mutate(dbp_K562_ratio = num_dbp_K562/460) #460

#Michael wrote this but I don't really get it. It didn't do anything interesting and the comparison df is wack.

#Okay now it's time to plot this shit.
ggplot(clean2_res_genes_2021, aes(x = gene_name, y = normalized_ratio_res21_res20)) +
  geom_point()

```

UNFILTERED PLOTS
```{r}
#Nina's plotting portions

# new data
g <- ggplot(peak_occurence_df_new, aes(x = number_of_dbp))

#AES layer will know to make a histogram since there is only one set of values for x.
g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA and lncRNA genes - HepG2") 


# 2020 data
g <- ggplot(peak_occurence_df_2020, aes(x = number_of_dbp))

#AES layer will know to make a histogram since there is only one set of values for x.
g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA and lncRNA genes - K562")

# 2020 data - only mRNAs
g <- ggplot(peak_occurence_df_2020 %>% filter(peak_occurence_df_2020$gene_type == 'protein_coding'), aes(x = number_of_dbp))

#AES layer will know to make a histogram since there is only one set of values for x.
g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA genes - K562") 


# 2020 data - both mRNAs and ncRNAs 
g <- ggplot(peak_occurence_df_2020, aes(x = number_of_dbp))+
  facet_wrap(gene_type ~ .)

g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA and lncRNA genes - K562") 



# 2020 data - both mRNAs and ncRNAs 
g <- ggplot(peak_occurence_df_2020, aes(x = number_of_dbp))+
  facet_wrap(expression ~ .)

g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA and lncRNA genes - K562") 



# 2020 data - in one image
ggplot(peak_occurence_df_2020, aes(x = number_of_dbp, fill = gene_type, color = gene_type)) +
   geom_density(alpha = 0.3)


# 2021 data - in one image --> main one
ggplot(peak_occurence_df_new, aes(x = number_of_dbp, fill = gene_type, color = gene_type)) +
   geom_density(alpha = 0.3)
```

PLOTTING RESERVOIRS
```{r}
# 2021 data - density plot

g <- ggplot(reservoir_new_data, aes(x = number_of_dbp, fill = gene_type, color = gene_type))

g + geom_density(alpha = 0.3) +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events of reservoirs",
          subtitle = "mRNA and lncRNA genes - HepG2") 


# scatterplot 
ggplot(comparison_df, aes(x = dbp_HepG2_ratio,
                         y = dbp_K562_ratio)) +
  geom_point()

ggplot(comparison_df, aes(x = num_dbp_HepG2,
                         y = num_dbp_K562)) +
  geom_point()

```

PLOT NON-RESERVOIRS


```{r}
g <- ggplot(res_genes_2021, aes(x = number_of_dbp, fill = gene_type, color = gene_type))

g + geom_density(alpha = 0.3) +
  xlab(expression("Number of DBPs - non-reservoirs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events of non-reservoirs",
          subtitle = "mRNA and lncRNA genes - HepG2") 


# make scatter plot 

ggplot(comparison_df, aes(x = dbp_HepG2_ratio,
                         y = dbp_K562_ratio)) +
  geom_point()

ggplot(comparison_df, aes(x = num_dbp_HepG2,
                         y = num_dbp_K562)) +
  geom_point()
```

FINDING WHICH DBPs ARE BINDING A GIVEN PROMOTER
```{r}
#2021 Data

high_binders_21 <- filter(peak_occurence_df, number_of_dbp >= 300)
xhigh_binders_21 <- as.data.frame(t(high_binders_21))

#Justin changed the intersect.functions file to make this work so I won't be able to make it work here. John isn't super into it anyways.
```


FINDING WHAT ZN FINGERS ARE BINDING TO
```{r}
head(num_peaks_df)
#I want to filter the ZFs from the dbd column, however not all the ZFs are named the same.


zinc_fingers <- num_peaks_df %>% filter(str_detect(dbd, "Z"))
head(zinc_fingers)

#localization of ZFs

z <- ggplot(zinc_fingers, aes(x = peaks_overlapping_mrna_promoters, y = peaks_overlapping_genebody))

z + geom_point(alpha = 0.3) +
  xlab(expression("Binding to mRNA promoters")) +
  ylab(expression("Binding to genebody")) +
  ggtitle("Localization of ZFs",
          subtitle = "mRNA and lncRNA genes - HepG2")

#ZFs binding mRNA vs lncRNA

z2 <- ggplot(zinc_fingers, aes(x = peaks_overlapping_mrna_promoters, y = peaks_overlapping_lncrna_promoters))

z2 + geom_point(alpha = 0.3) +
  xlab(expression("Binding to mRNA promoters")) +
  ylab(expression("Binding to lncRNA promoters")) +
  ggtitle("Preferences of ZFs",
          subtitle = "mRNA and lncRNA genes - HepG2")

```

JOHN'S CODE
```{r}
occurence_matrix <- read.table("results/lncrna_mrna_promoter_peak_occurence_matrix.tsv")

super_promoter <- occurence_matrix[, colSums(occurence_matrix) > 350]

super_promoter_dbps <- data.frame(dbp = rownames(super_promoter), num_super_promoter_overlaps = rowSums(super_promoter))

num_peaks_df <- read.csv("results/num_peaks_df.csv")

super_promoter_features <- merge(num_peaks_df, super_promoter_dbps)

super_promoter_features <- dplyr::select(super_promoter_features, dbp, num_super_promoter_overlaps, everything() )

super_promoter_features <- super_promoter_features %>%
  mutate(percent_super_prom_ov = num_super_promoter_overlaps/peaks_overlapping_promoters * 100, 
         percent_of_total_peaks_at_super_prom = num_super_promoter_overlaps/num_peaks * 100,
         zincfinger = ifelse(dbd == "C2H2 ZF", "C2H2 ZF", "Other"))

ggplot(super_promoter_features, aes(x = percent_super_prom_ov, color = zincfinger)) +
  geom_density()

ggplot(super_promoter_features, aes(x = percent_of_total_peaks_at_super_prom, y = percent_super_prom_ov)) + 
  geom_point()

write.csv(super_promoter_features, "results/super_promoter_features.csv")
```