---
title: "Global peak properties"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GenomicRanges)
source("util/intersect_functions.R")
source("util/plotting_functions.R")
source("util/_setup.R")
library(Gviz)
library(ggplot2)

```

Open dataframe

```{r}

# scatterplot x: K562 % dbp and HepG

peak_occurence_df_2020 <- read.csv(file = '/scratch/Shares/rinnclass/data/2020_peak_occurence_df.csv')
head(peak_occurence_df_2020)

peak_occurence_df_new <- read.csv(file = '/scratch/Shares/rinnclass/Victor/CLASS_2021/analysis/01_global_peak_properties/results/peak_occurence_dataframe.csv')
head(peak_occurence_df_new)


```

plot Promoter binding events 


```{r}
# new data
g <- ggplot(peak_occurence_df_new, aes(x = number_of_dbp))

#AES layer will know to make a histogram since there is only one set of values for x.
g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA and lncRNA genes - HepG2") 


# 2020 data
g <- ggplot(peak_occurence_df_2020, aes(x = number_of_dbp))

#AES layer will know to make a histogram since there is only one set of values for x.
g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA and lncRNA genes - K562") 

# 2020 data - only mRNAs
g <- ggplot(peak_occurence_df_2020 %>% filter(peak_occurence_df_2020$gene_type == protein_coding), aes(x = number_of_dbp))

#AES layer will know to make a histogram since there is only one set of values for x.
g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA genes - K562") 


# 2020 data - both mRNAs and ncRNAs 
g <- ggplot(peak_occurence_df_2020, aes(x = number_of_dbp))+
  facet_wrap(gene_type ~ .)

g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA and lncRNA genes - K562") 



# 2020 data - both mRNAs and ncRNAs 
g <- ggplot(peak_occurence_df_2020, aes(x = number_of_dbp))+
  facet_wrap(expression ~ .)

g + geom_density(alpha = 0.2, color = "#424242", fill = "#424242") +
  theme_paperwhite() +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events",
          subtitle = "mRNA and lncRNA genes - K562") 




# 2020 data - in one image
ggplot(peak_occurence_df_2020, aes(x = number_of_dbp, fill = gene_type, color = gene_type)) +
   geom_density(alpha = 0.3)


# 2021 data - in one image
ggplot(peak_occurence_df_new, aes(x = number_of_dbp, fill = gene_type, color = gene_type)) +
   geom_density(alpha = 0.3)

```


```{r}
# filter for reservoirs

reservoir_list_2020 <- peak_occurence_df_2020 %>% filter(peak_occurence_df_2020$reservoir == 1)
gene_w_reservoirs <-reservoir_list_2020$gene_id

reservoir_new_data <- peak_occurence_df_new %>% filter(peak_occurence_df_new$gene_id %in% gene_w_reservoirs)

# plot 
# 2021 data - in one image

g <- ggplot(reservoir_new_data, aes(x = number_of_dbp, fill = gene_type, color = gene_type))

g + geom_density(alpha = 0.3) +
  xlab(expression("Number of DBPs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events of reservoirs",
          subtitle = "mRNA and lncRNA genes - HepG2") 


# make scatter plot 
reservoir_new_data

num_dbp_2020 <- peak_occurence_df_2020 %>%
  dplyr::select(gene_id, gene_type, number_of_dbp) %>%
  dplyr::rename(num_dbp_K562 = number_of_dbp)
num_reservoir_new_data <- reservoir_new_data %>%
  dplyr::select(gene_id, number_of_dbp) %>%
  dplyr::rename(num_dbp_HepG2 = number_of_dbp)


names(peak_occurence_df_2020)
names(gene_w_reservoirs)
comparison_df <- merge(num_dbp_2020, num_reservoir_new_data)


comparison_df <-comparison_df %>% mutate(dbp_HepG2_ratio = num_dbp_HepG2/460) #161
comparison_df <- comparison_df %>% mutate(dbp_K562_ratio = num_dbp_K562/161) #460



# new data

ggplot(comparison_df, aes(x = dbp_HepG2_ratio,
                         y = dbp_K562_ratio)) +
  geom_point()

ggplot(comparison_df, aes(x = num_dbp_HepG2,
                         y = num_dbp_K562)) +
  geom_point()



#### new data
comparison_df <-comparison_df %>% mutate(dbp_HepG2_ratio = num_dbp_HepG2/406*100) #180
comparison_df <- comparison_df %>% mutate(dbp_K562_ratio = num_dbp_K562/111*100) #460


ggplot(comparison_df, aes(x = dbp_HepG2_ratio,
                         y = dbp_K562_ratio)) +
  geom_point()

ggplot(comparison_df, aes(x = num_dbp_HepG2,
                         y = num_dbp_K562)) +
  geom_point()




# non - reservoirs
reservoir_list_2020 <- peak_occurence_df_2020 %>% filter(peak_occurence_df_2020$reservoir == 0)
gene_w_reservoirs <-reservoir_list_2020$gene_id

reservoir_new_data <- peak_occurence_df_new %>% filter(peak_occurence_df_new$gene_id %in% gene_w_reservoirs)

# plot 
# 2021 data - in one image

g <- ggplot(reservoir_new_data, aes(x = number_of_dbp, fill = gene_type, color = gene_type))

g + geom_density(alpha = 0.3) +
  xlab(expression("Number of DBPs - non-reservoirs")) +
  ylab(expression("Density")) +
  ggtitle("Promoter binding events of non-reservoirs",
          subtitle = "mRNA and lncRNA genes - HepG2") 


# make scatter plot 
reservoir_new_data

num_dbp_2020 <- peak_occurence_df_2020 %>%
  dplyr::select(gene_id, gene_type, number_of_dbp) %>%
  dplyr::rename(num_dbp_K562 = number_of_dbp)
num_reservoir_new_data <- reservoir_new_data %>%
  dplyr::select(gene_id, number_of_dbp) %>%
  dplyr::rename(num_dbp_HepG2 = number_of_dbp)


names(peak_occurence_df_2020)
names(gene_w_reservoirs)
comparison_df <- merge(num_dbp_2020, num_reservoir_new_data)


comparison_df <-comparison_df %>% mutate(dbp_HepG2_ratio = num_dbp_HepG2/460) #180
comparison_df <- comparison_df %>% mutate(dbp_K562_ratio = num_dbp_K562/180) #460




ggplot(comparison_df, aes(x = dbp_HepG2_ratio,
                         y = dbp_K562_ratio)) +
  geom_point()

ggplot(comparison_df, aes(x = num_dbp_HepG2,
                         y = num_dbp_K562)) +
  geom_point()

```

```{r}
human_tfs <- readxl::read_excel("/scratch/Shares/rinnclass/data/mmc2.xlsx",
                                sheet = 2, skip = 1)
names(human_tfs)[4] <- "is_tf"

length(which(tolower(num_peaks_df$dbp) %in% tolower(human_tfs$Name)))


human_tfs <- human_tfs[tolower(human_tfs$Name) %in% tolower(num_peaks_df$dbp), 1:4]
names(human_tfs) <- c("ensembl_id",
                      "dbp",
                      "dbd",
                      "tf")

```

```{r}

num_dbps_threshold <- 299

highly_bound_genes <- peak_occurence_df_new[sapply(peak_occurence_df_new, number_of_dbp) > num_dbps_threshold]



highly_bound_genes <- peak_occurence_df_new %>% filter(peak_occurence_df_new$number_of_dbp > 299)

highly_bound_genes <- highly_bound_genes$gene_id

highly_bound_genes <- as.data.frame(t(highly_bound_genes))


```

subsetting occurrence matrix by reservoirs or high binders make a cutoff, do column or row sums

for ewachdbp, how many high binding promoters it bound

find promoters with high binding, 











