---
title: "Class10_exercise"
author: "Katy Walsh"
date: "3/1/2021"
output: html_document
editor_options: 
  chunk_output_type: console
---

Directions:
pull 4 DBPs (2 replicates each) from rinnclass/data and copy into a folder to just run through those
make consensus peaks
create promoter regions - how many binding sites with lncRNA and mRNAs and all promoters
count peaks per feature
make a num_peaks_df to track


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GenomicRanges)
source("util/intersect_functions.R")
source("util/plotting_functions.R")
source("util/_setup.R")
library(Gviz)
#library(ggpubr)
library(ggplot2)
```


```{r}
#copy the first 4 DBPs (8 files) in terminal 
# "/scratch/Shares/rinnclass/data/peaks" to "/Users/niri2724/CLASS/Nina/broad_peaks"

#make a list of files in the folder
fl <- list.files("/scratch/Shares/rinnclass/Nina/broad_peaks", full.names=TRUE)
#make G ranges object with files from the folder
test_peaks <- lapply(fl, rtracklayer::import)

#add metadata names to the test_peaks G-ranges
names(test_peaks) <- sapply(test_peaks, function(x){
  unlist(strsplit(x$name, "_"))[[1]]
})

#make consensus peaks (needed to edit the consensus peaks function to work for a different path)
test_consensus_peaks <- create_consensus_peaks(broadpeakfilepath = "/scratch/Shares/rinnclass/Nina/broad_peaks")

#check if the correct names are there
names(test_consensus_peaks)

```


```{r}
#make a df to keep info about peaks data per DBP
test_num_peaks_df <- data.frame("dbp" = names(test_consensus_peaks),
                           "num_peaks" = sapply(test_consensus_peaks, length))

#filtered out any DBPs that have less than 500 binding sites in the genome
test_filtered_consensus_peaks <- test_consensus_peaks[test_num_peaks_df$num_peaks > 500]

#makes hist for the 5 DBPs in our file (not very interesting)
g <- ggplot(test_num_peaks_df, aes(x = num_peaks)) + 
  geom_histogram(bins = 70)
show(g)

#can output consensus peak results as bed files
for(i in 1:length(filtered_consensus_peaks)) {
  rtracklayer::export(filtered_consensus_peaks[[i]], paste0("results/filtered_peaks/", names(filtered_consensus_peaks)[i], 
"_consensus_peaks_filter.bed"))
}

#update peaks df to remove anything that was removed by the filter
test_num_peaks_df <- test_num_peaks_df %>% filter(dbp %in% names(test_filtered_consensus_peaks))

#add peak widths to the peaks df (total bp bound by each DBP)
test_num_peaks_df$total_peak_length <- sapply(test_filtered_consensus_peaks, function(x) sum(width(x)))

```

```{r}
#download genome annotations
gencode_gr <- rtracklayer::import("/Shares/rinn_class/data/genomes/human/gencode/v32/gencode.v32.annotation.gtf")

#make list of all promoters and export
lncrna_mrna_promoters <- get_promoter_regions(gencode_gr, biotype = c("lncRNA", "protein_coding"))
rtracklayer::export(lncrna_mrna_promoters, "results/lncrna_mrna_promoters.gtf")

#make lists of lncRNA promoters and mRNA promters seperately
lncrna_promoters <- get_promoter_regions(gencode_gr, biotype = "lncRNA")
rtracklayer::export(lncrna_promoters, "results/lncrna_promoters.gtf")

mrna_promoters <- get_promoter_regions(gencode_gr, biotype = "protein_coding")
rtracklayer::export(mrna_promoters, "results/mrna_promoters.gtf")



##now use those lists to see what overlapps with each promoter
test_promoter_peak_counts <- count_peaks_per_feature(lncrna_mrna_promoters, test_filtered_consensus_peaks, type = "counts")

#add column for number of total promoters bound by each DBP
test_num_peaks_df$peaks_overlapping_promoters <- rowSums(test_promoter_peak_counts)

#add column for lncRNA Promoters
test_num_peaks_df$peaks_overlapping_lncrna_promoters <- rowSums(test_promoter_peak_counts[,lncrna_promoters$gene_id])

#add column for mRNA promoters
test_num_peaks_df$peaks_overlapping_mrna_promoters <- rowSums(test_promoter_peak_counts[,mrna_promoters$gene_id])

##now all data is stored in the test_num_peaks_df so let's save that
write_csv(test_num_peaks_df, "/scratch/Shares/rinnclass/Katy/CLASS_2021/results/num_peaks_exercise.csv")

```






