---
title: "Global peak properties"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(GenomicRanges)
library(Gviz)
library(ggpubr)
library(BiocManager)
    install("BSgenome.Hsapiens.UCSC.hg38")
BiocManager::install("biomartr")
library(biomartr)
library(regioneR)
library(ggdendro)
    
source("/scratch/Shares/rinnclass/Justin/util/intersect_functions.R")
source("/scratch/Shares/rinnclass/Justin/CLASS_2021/util/plotting_functions.R")
source("/scratch/Shares/rinnclass/Justin/CLASS_2021/util/_setup.R")
```

```{r}
base_path <- "/scratch/Shares/rinnclass/Justin/CLASS_2021/analysis/00_consensus_peaks/results"
peak_list <- import_peaks(file.path(base_path,
                                    "filtered_consensus/"))
# Import gencode
lncrna_promoters <- rtracklayer::import(file.path(base_path,
                                                  "promoters/lncrna_promoters.gtf"))
mrna_promoters <- rtracklayer::import(file.path(base_path,
                                                "promoters/mrna_promoters.gtf"))
lncrna_mrna_promoters <- rtracklayer::import(file.path(base_path,
                                                "promoters/lncrna_mrna_promoters.gtf"))
lncrna_matrix <- count_peaks_per_feature(lncrna_promoters, 
                                         peak_list, type = "occurrence")
mrna_matrix <- count_peaks_per_feature(mrna_promoters, 
                                       peak_list, type = "occurrence")

```

```{r}
num_peaks_df <- data.frame("dbp" = rownames(lncrna_matrix),
                           "total_number_of_peaks" = sapply(peak_list, length),
                           "lncrna" = rowSums(lncrna_matrix),
                           "mrna" = rowSums(mrna_matrix))

summary(lncrna_matrix)
```

```{r}
occ_matrix <- read.table("~/CLASS/Justin/CLASS_2021/analysis/01_global_peak_properties/results/lncrna_mrna_promoter_peak_occurence_matrix.tsv")

super_promoter <- occ_matrix[,colSums(occ_matrix) > 350]

super_promoter_dbps <- data.frame(dbp = rownames(super_promoter), num_super_promoter_overlaps = rowSums(super_promoter))

num_peaks_df <- read.csv("~/CLASS/Justin/CLASS_2021/analysis/01_global_peak_properties/results/num_peaks_df.csv")
super_promoter_features <- merge(num_peaks_df, super_promoter_dbps, by = "dbp")
super_promoter_features <- dplyr::select(super_promoter_features, dbp, num_super_promoter_overlaps, everything() )
super_promoter_features <- super_promoter_features %>%
  mutate(percent_super_prom_ov = num_super_promoter_overlaps/peaks_overlapping_promoters * 100, 
         percent_of_total_peaks_at_super_prom = num_super_promoter_overlaps/num_peaks * 100,
         zincfinger = ifelse(grepl(" ZF", dbd), "Other"))
ggplot(super_promoter_features, aes(x = percent_super_prom_ov, color = zincfinger)) +
  geom_density()
ggplot(super_promoter_features, aes(x = percent_of_total_peaks_at_super_prom, y = percent_super_prom_ov)) + 
  geom_point()
write.csv(super_promoter_features, "~/CLASS/Justin/CLASS_2021/analysis/03_reservoir_binding_DBP/results/super_promoter_features.csv")


```



